---
# name: Install MySQL for production ready server

- name: Set MySQL root password before installing
  become: yes
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{MySQL_root_pass | quote}}' vtype='password'

- name: Confirm MySQL root password before installing
  become: yes
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{MySQL_root_pass | quote}}' vtype='password'

- name: Install MySQL
  apt: package={{ item }} state=present force=yes update_cache=yes cache_valid_time=3600
  when: ansible_os_family == 'Debian'
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Deletes anonymous MySQL server user for localhost
  become: yes
  mysql_user: user="" state="absent" login_password="root" login_user="root"

- name: Secures the MySQL root user
  become: yes
  mysql_user: user="root" password="{{ MySQL_root_pass }}" host="{{ item }}" login_password="root" login_user="root"
  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"
